apiVersion: apps/v1
kind: Deployment
metadata: 
  name: replica-1
spec:
  replicas: 3
  selector:
    matchLabels:       # Corrected from "MatchLabels" (must be lowercase)
      project: swiggy
  template:
    metadata:          # Corrected from "matadata" (spelling error)
      labels:
        project: swiggy
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80

 
